sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tKsAL2C9xhohjKgwHjb
    access-key-secret: iSRqWjhSSLhtJAyX49K2eL5YDcgbRO
    bucket-name: sky-take-out0214
  redis:
    host: localhost
    port: 6379
    password: 123456
  wechat:
    appid: wxf1ed0641dee8e3d0
    secret: 2e16ad54030a62015081afd0c69ab936